### PR TITLE
feat: added new labels including "first-timers-only" to gemfile

### PR DESCRIPTION
**Pull request by DominiqueFlabbi**
Added the following labels to the gemfile: 
- `first-timers-only`
- `up-for-grabs`
- `help wanted`

Set a common colour, and updated the documentation to reflect a new category called "Universal Labels". 
Addresses issue #20. 

**Reviewers be aware**
The `help wanted` label was previously being removed automatically, I stripped this line from the auto-removal piece of the code. Hope that's okay.

### CODE REVIEW

**Comment by DominiqueFlabbi** [comment]
Oh interesting..... I must have an extension that auto-applied formatting across the roadmap.md file.

**Comment by madiedgar** [comment]
Awesome @DominiqueFlabbi! Thanks for this! I will wait until Oct. 1st to merge so you get your hacktoberfest credit. 🎉

**Comment by madiedgar** [comment]
@DominiqueFlabbi I need to update the **special gift** link today. I'll get you the updated link soon 😄 THANK YOU SO MUCH FOR CONTRIBUTING!!! ❤️

**Comment by madiedgar** [comment]
Hey @DominiqueFlabbi thanks again for your contribution! We'd love to show you how appreciative we are of your help by sending you a [small gift](https://madi357705.typeform.com/to/wzub4R). THANK YOU AGAIN!!! 🎉

**Pull request merged**
