### PR TITLE
docs: add entries for more python keywords

### PR DESCRIPTION
**Pull request by sameshl**
Add description for some more python keywords
I couldn't find an appropriate category for some python keywords so I added `inbuilt function`.
Let me know if any changes are to be made, I will make them ASAP.

### CODE REVIEW

**Comment by madiedgar** [comment]
Hey @sameshl 👋 thanks again for this! If you still need more PR's for Hacktoberfest, feel free to add entries for any other programming languages. 👍

**Comment by sameshl** [comment]
@madiedgar Would love to contribute :+1:

**Comment by sameshl** [comment]
@madiedgar Just one small thing that I noticed, the `special gift` link in the welcome bot reply is broken.

**Comment by madiedgar** [comment]
ooops! My bad, try [this link](https://madi357705.typeform.com/to/wzub4R) 👍

**Pull request merged**
